name = "uno"
main = "worker/index.ts"
compatibility_date = "2026-05-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[durable_objects.bindings]]
name = "GAME"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[observability]
enabled = true

[dev]
ip = "0.0.0.0"
port = 3000
